MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Controllers/BinHierarchyController.cs
using CodeLock.Areas.Master.Repository;
using CodeLock.Models;
using Microsoft.CSharp.RuntimeBinder;
using Secure_Coding.MvcSecurityExtensions;
using System;
using System.Collections.Generic;
using System.Net;
using System.Runtime.CompilerServices;
using System.Web.Mvc;

namespace CodeLock.Areas.Master.Controllers
{
  public class BinHierarchyController : Controller
  {
    private readonly IBinHierarchyRepository binHierarchyRepository;
    private readonly IWarehouseRepository warehouseRepository;

        public BinHierarchyController()
        {
        }

        public BinHierarchyController(IBinHierarchyRepository _binHierarchyRepository, IWarehouseRepository _warehouseRepository)
        {
            this.binHierarchyRepository = _binHierarchyRepository;
            this.warehouseRepository = _warehouseRepository;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.binHierarchyRepository.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Index()
        {
            return base.View(this.binHierarchyRepository.GetAll());
        }

        public ActionResult Insert()
        {
            MasterBinHierarchy masterBinHierarchy = new MasterBinHierarchy();
            ((dynamic)base.ViewBag).WarehouseList = this.warehouseRepository.GetVirtualLoginWarehouseList(SessionUtility.LoginUserId);
            return base.View(masterBinHierarchy);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateAntiModelInjection("BinHierarchyId")]
        public ActionResult Insert(MasterBinHierarchy objMasterBinHierarchy)
        {
            ActionResult action;
            if (!base.ModelState.IsValid)
            {
                action = base.View(objMasterBinHierarchy);
            }
            else
            {
                objMasterBinHierarchy.EntryBy = SessionUtility.LoginUserId;
                byte num = this.binHierarchyRepository.Insert(objMasterBinHierarchy);
                action = base.RedirectToAction("View", new { id = num });
            }
            return action;
        }

        [HttpPost]
        [ValidateAntiModelInjection("BinHierarchyId")]
        public JsonResult IsBinHierarchyNameAvailable(MasterBinHierarchy objMasterBinHierarchy)
        {
            JsonResult jsonResult = base.Json(this.binHierarchyRepository.IsBinHierarchyNameAvailable(objMasterBinHierarchy.BinHierarchyName, (short)objMasterBinHierarchy.BinHierarchyId));
            return jsonResult;
        }

        public ActionResult Update(byte? id)
        {
            ActionResult httpStatusCodeResult;
            int? nullable;
            int? nullable1;
            byte? nullable2 = id;
            if (nullable2.HasValue)
            {
                nullable1 = new int?((int)nullable2.GetValueOrDefault());
            }
            else
            {
                nullable = null;
                nullable1 = nullable;
            }
            nullable = nullable1;
            if (nullable.HasValue)
            {
                ((dynamic)base.ViewBag).WarehouseList = this.warehouseRepository.GetVirtualLoginWarehouseList(SessionUtility.LoginUserId);
                httpStatusCodeResult = base.View(this.binHierarchyRepository.GetDetailById(id.Value));
            }
            else
            {
                httpStatusCodeResult = new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return httpStatusCodeResult;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateAntiModelInjection("BinHierarchyId")]
        public ActionResult Update(MasterBinHierarchy objMasterBinHierarchy)
        {
            ActionResult action;
            if (!base.ModelState.IsValid)
            {
                action = base.View(objMasterBinHierarchy);
            }
            else
            {
                objMasterBinHierarchy.UpdateBy = new short?(SessionUtility.LoginUserId);
                byte num = this.binHierarchyRepository.Update(objMasterBinHierarchy);
                action = base.RedirectToAction("View", new { id = num });
            }
            return action;
        }

        public ActionResult View(byte? id)
        {
            ActionResult httpStatusCodeResult;
            int? nullable;
            int? nullable1;
            byte? nullable2 = id;
            if (nullable2.HasValue)
            {
                nullable1 = new int?((int)nullable2.GetValueOrDefault());
            }
            else
            {
                nullable = null;
                nullable1 = nullable;
            }
            nullable = nullable1;
            if (nullable.HasValue)
            {
                httpStatusCodeResult = base.View(this.binHierarchyRepository.GetDetailById(id.Value));
            }
            else
            {
                httpStatusCodeResult = new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return httpStatusCodeResult;
        }



    }
}

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/BinHierarchy/Index.cshtml
@model IEnumerable<CodeLock.Models.MasterBinHierarchy>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="widget-wrap material-table-widget">
    <table id="dtBinHierarchy">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.BinHierarchyName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.WarehouseName)
                </th>
                <th class="td-center" data-sort-ignore="true" data-hide="phone">Action</th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.EntryByName)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.EntryDate)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.UpdateByName)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.UpdateDate)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.BinHierarchyName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.WarehouseName)
                    </td>
                    <td class="td-center">
                        <div class="btn-toolbar" role="toolbar">
                            <div class="btn-group" role="group">
                                <a class="btn btn-default btn-sm m-user-edit" href="@Url.Action("Update", new { id = item.BinHierarchyId })"><span class="zmdi zmdi-edit"></span></a>
                                <a class="btn btn-default btn-sm m-user-edit" href="@Url.Action("View", new { id = item.BinHierarchyId })"><span class="fa fa-file"></span></a>
                            </div>
                        </div>
                    </td>
                    <td style="display:none">
                        @Html.DisplayFor(modelItem => item.EntryByName)
                    </td>
                    <td style="display:none">
                        @item.EntryDate.ToDisplayDateTime()
                    </td>
                    <td style="display:none">
                        @Html.DisplayFor(modelItem => item.UpdateByName)
                    </td>
                    <td style="display:none">
                        @item.UpdateDate.ToDisplayDateTime()
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        SetPageLoad('Bin Hierarchy', 'List', 'filter', 'Add New', '@Url.Action("Insert")');
        LoadDataTable('dtBinHierarchy', true, true, true);
    });
</script>

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/BinHierarchy/Insert.cshtml
@model CodeLock.Models.MasterBinHierarchy
@using Secure_Coding.MvcSecurityExtensions;
@{
    ViewBag.Title = "Insert";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Insert", "BinHierarchy", FormMethod.Post, new { @class = "j-forms" }))
{
    @Html.AntiForgeryToken()
    @Html.AntiModelInjectionFor(m => m.BinHierarchyId)
    @Html.Hidden("BinHierarchyId", 0)
    <div class="widget-wrap">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.BinHierarchyName, new { @class = "label" })
                    <div class="input">
                        @Html.TextBoxFor(model => model.BinHierarchyName, new { @class = "form-control", @id = "txtBinHierarchyName" })
                    </div>
                    @Html.ValidationMessageFor(model => model.BinHierarchyName)
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.WarehouseId, new { @class = "label" })
                    <div class="select">
                        @Html.DropDownListFor(model => model.WarehouseId, new SelectList(ViewBag.WarehouseList, "Value", "Name"), "Select Warehouse", new { @class = "form-control", @id = "ddlWarehouse" })
                        <i></i>
                    </div>
                    @Html.ValidationMessageFor(model => model.WarehouseId)
                </div>
            </div>
        </div>

        <div class="form-footer">
            <button type="submit" class="btn btn-success primary-btn" tabindex="3">Create</button>
        </div>
    </div>
}
<script>
    $(document).ready(function () {
        SetPageLoad('Bin Hierarchy', 'Create', 'txtBinHierarchyName', 'Goto List', '@Url.Action("Index")');
    });
</script>

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/BinHierarchy/Update.cshtml
@model CodeLock.Models.MasterBinHierarchy
@using Secure_Coding.MvcSecurityExtensions;
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Update", "BinHierarchy", FormMethod.Post, new { @class = "j-forms" }))
{
    @Html.AntiForgeryToken()
    @Html.AntiModelInjectionFor(model => model.BinHierarchyId)
    @Html.HiddenFor(model => model.BinHierarchyId)
    <div class="widget-wrap">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.BinHierarchyName, new { @class = "label" })
                    <div class="input">
                        @Html.TextBoxFor(model => model.BinHierarchyName, new { @class = "form-control", @id = "txtBinHierarchyName" })
                    </div>
                    @Html.ValidationMessageFor(model => model.BinHierarchyName)
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.WarehouseId, new { @class = "label" })
                    <div class="select">
                        @Html.DropDownListFor(model => model.WarehouseId, new SelectList(ViewBag.WarehouseList, "Value", "Name"), "Select Warehouse", new { @class = "form-control", @id = "ddlWarehouse" })
                        <i></i>
                    </div>
                    @Html.ValidationMessageFor(model => model.WarehouseId)
                </div>
            </div>
        </div>

        <div class="form-footer">
            <button type="submit" class="btn btn-success primary-btn" tabindex="3">Update</button>
        </div>
    </div>
}

<script>
    $(document).ready(function () {
        SetPageLoad('Bin Hierarchy', 'Update', 'txtBinHierarchyName', 'Goto List', '@Url.Action("Index")', 'Add New', '@Url.Action("Create")', 'View Detail', '@Url.Action("View", new { id = Model.BinHierarchyId })');
    });
</script>

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/BinHierarchy/View.cshtml
@model CodeLock.Models.MasterBinHierarchy
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="widget-wrap">
    <div class="row">
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.BinHierarchyName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.BinHierarchyName)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.WarehouseName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.WarehouseName)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.EntryByName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.EntryByName)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.EntryDate)
                </dt>
                <dd>
                    @Model.EntryDate.ToDisplayDateTime()
                </dd>
            </dl>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.UpdateByName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.UpdateByName)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.UpdateDate)
                </dt>
                <dd>
                    @Model.UpdateDate.ToDisplayDateTime()
                </dd>
            </dl>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        SetPageLoad('Bin Hierarchy', 'View Detail', '', 'Goto List', '@Url.Action("Index")', 'Add New', '@Url.Action("Insert")', 'Update', '@Url.Action("Update", new { id = Model.BinHierarchyId })');
    });
</script>