MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Controllers/TyrePositionController.cs
using CodeLock.Areas.Master.Repository;
using CodeLock.Areas.Operation.Repository;
using CodeLock.Models;
using Secure_Coding.MvcSecurityExtensions;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using System.Web.UI;

namespace CodeLock.Areas.Master.Controllers
{
    public class TyrePositionController : Controller
    {
        private readonly ITyrePositionRepository tyrePositionRepository;
        private readonly IVehicleTypeRepository vehicleTypeRepository;
        private readonly IGeneralRepository generalRepository;

        public TyrePositionController(ITyrePositionRepository _tyrePositionRepository, IVehicleTypeRepository _vehicleTypeRepository, IGeneralRepository _generalRepository)
        {
            this.tyrePositionRepository = _tyrePositionRepository;
            this.vehicleTypeRepository = _vehicleTypeRepository;
            this.generalRepository = _generalRepository;
        }
        public ActionResult Index()
        {
            List<MasterTyrePosition> objMasterTyrePosition = new List<MasterTyrePosition>();
            objMasterTyrePosition = (List<MasterTyrePosition>)tyrePositionRepository.GetAll();
            return View(objMasterTyrePosition);

        }
        public ActionResult Insert()
        {
            MasterTyrePosition objMasterTyrePosition = new MasterTyrePosition();
            ((dynamic)base.ViewBag).VehicleTypeList = this.vehicleTypeRepository.GetVehicleTypeList();
            ((dynamic)base.ViewBag).PositionCategoryTypeList = this.generalRepository.GetByIdList(101);
            return View(objMasterTyrePosition);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateAntiModelInjection("TyrePositionid")]
        public ActionResult Insert(MasterTyrePosition objMasterTyrePosition)
        {
            if (ModelState.IsValid)
            {
                objMasterTyrePosition.EntryBy = SessionUtility.LoginUserId;
                short TyrePositionid = tyrePositionRepository.Insert(objMasterTyrePosition);
                return RedirectToAction("View", new { id = TyrePositionid });
            }
            return View(objMasterTyrePosition);
        }
        public ActionResult Update(short? id)
        {
            short? nullable = id;
            ((dynamic)base.ViewBag).VehicleTypeList = this.vehicleTypeRepository.GetVehicleTypeList();
            ((dynamic)base.ViewBag).PositionCategoryTypeList = this.generalRepository.GetByIdList(101);
            if (!(nullable.HasValue ? new int?((int)nullable.GetValueOrDefault()) : new int?()).HasValue)
                return (ActionResult)new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            return (ActionResult)this.View((object)this.tyrePositionRepository.GetById(id.Value));
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [ValidateAntiModelInjection("TyrePositionid")]
        public ActionResult Update(MasterTyrePosition objMasterTyrePosition)
        {
            if (!this.ModelState.IsValid)
                return (ActionResult)this.View((object)objMasterTyrePosition);
            objMasterTyrePosition.UpdateBy = new short?(SessionUtility.LoginUserId);
            return (ActionResult)this.RedirectToAction("View", (object)new
            {
                id = this.tyrePositionRepository.Update(objMasterTyrePosition)
            });
        }
        public ActionResult View(short? id)
        {
            ActionResult httpStatusCodeResult;
            int? nullable;
            int? nullable1;
            short? nullable2 = id;
            if (nullable2.HasValue)
            {
                nullable1 = new int?(nullable2.GetValueOrDefault());
            }
            else
            {
                nullable = null;
                nullable1 = nullable;
            }
            nullable = nullable1;
            if (nullable.HasValue)
            {
                httpStatusCodeResult = base.View(this.tyrePositionRepository.GetById(id.Value));
            }
            else
            {
                httpStatusCodeResult = new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return httpStatusCodeResult;
        }
    }

}

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/TyrePosition/Index.cshtml
@model IEnumerable<CodeLock.Models.MasterTyrePosition>

    @{
        ViewBag.Title = "TyrePosition List";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    <div class="widget-wrap material-table-widget">
        <table id="dtTyrePosition">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.TyrePositionid)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.VehicleTypeName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PositionCategoryName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PositionShortCode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TyrePositionDescription)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </th>
                    <th class="td-center" data-sort-ignore="true" data-hide="phone">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.TyrePositionid)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.VehicleTypeName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PositionCategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PositionShortCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TyrePositionDescription)
                        </td>
                        <td>
                            @Html.Label("", item.IsActive == true ? "Yes" : "No", new { @class = item.IsActive == true ? "label label-success" : "label label-default" })
                        </td>
                        <td class="td-center">
                            <div class="btn-toolbar" role="toolbar">
                                <div class="btn-group" role="group">
                                    <a class="btn btn-default btn-sm m-user-edit" href="@Url.Action("Update", new { id = item.TyrePositionid })"><span class="zmdi zmdi-edit"></span></a>
                                    <a class="btn btn-default btn-sm m-user-edit" href="@Url.Action("View", new { id = item.TyrePositionid })"><span class="fa fa-file"></span></a>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <script>
    $(document).ready(function () {
        SetPageLoad('TyrePosition', 'List', 'filter', 'Add New', '@Url.Action("Insert")');
        LoadDataTable('dtTyrePosition', true, true, true);
    });
    </script>

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/TyrePosition/Insert.cshtml
@model CodeLock.Models.MasterTyrePosition
@using CodeLock.Models
@using Secure_Coding.MvcSecurityExtensions;
@{
    ViewBag.Title = "TyrePosition Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Insert", "TyrePosition", FormMethod.Post, new { @class = "j-forms" }))
{
    @Html.AntiForgeryToken()
    @Html.AntiModelInjectionFor(m => m.TyrePositionid)
    @Html.Hidden("TyrePositionid", 0)

<div class="widget-wrap">
    <div class="row">
        <div class="col-sm-3">
            <div class="form-group">
                @Html.LabelFor(model => model.VehicleTypeId, new { @class = "label" })
                <div class="select">
                    @Html.DropDownListFor(model => model.VehicleTypeId, new SelectList(ViewBag.VehicleTypeList, "Value", "Name"), "Select Vehicle Type", new { @class = "form-control", @id = "ddlVehicleType" })
                    <i></i>
                </div>
                @Html.ValidationMessageFor(model => model.VehicleTypeId)
            </div>
        </div>
        <div class="col-sm-3">
            <div class="form-group">
                @Html.LabelFor(model => model.PositionCategoryId, new { @class = "label" })
                <div class="select">
                    @Html.DropDownListFor(model => model.PositionCategoryId, new SelectList(ViewBag.PositionCategoryTypeList, "Value", "Name"), "Select PositionCategory", new { @class = "form-control", @id = "ddlPositionCategory" })
                    <i></i>
                </div>
                @Html.ValidationMessageFor(model => model.PositionCategoryId)

            </div>
        </div>
        <div class="col-sm-3">
            <div class="form-group">
                @Html.LabelFor(model => model.PositionShortCode, new { @class = "label" })
                <div class="input">
                    @Html.TextBoxFor(model => model.PositionShortCode, new { @class = "form-control", @id = "txtPositionShortCode" })
                </div>
                @Html.ValidationMessageFor(model => model.PositionShortCode)
            </div>
        </div>
        <div class="col-sm-3">
            <div class="form-group">
                @Html.LabelFor(model => model.TyrePositionDescription, new { @class = "label" })
                <div class="input">
                    @Html.TextBoxFor(model => model.TyrePositionDescription, new { @class = "form-control", @id = "txtTyrePositionDescription" })
                </div>
                @Html.ValidationMessageFor(model => model.TyrePositionDescription)
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, new { @class = "label" })
                <label class="checkbox">
                    @Html.CheckBoxFor(model => model.IsActive)
                    <i></i>
                </label>
            </div>
        </div>
    </div>

    <div class="form-footer">
        <button type="submit" class="btn btn-success primary-btn" tabindex="3">Create</button>
    </div>
</div>

}
<script>
    $(document).ready(function () {
        SetPageLoad('TyrePosition', 'Create', 'ddlVehicleType', 'Goto List', '@Url.Action("Index")');
    });
</script>

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/TyrePosition/Update.cshtml
@model CodeLock.Models.MasterTyrePosition
@using Secure_Coding.MvcSecurityExtensions;
@{
    ViewBag.Title = "TyrePosition Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Update", "TyrePosition", FormMethod.Post, new { @class = "j-forms" }))
{
    @Html.AntiForgeryToken()
    @Html.AntiModelInjectionFor(model => model.TyrePositionid)
    @Html.HiddenFor(model => model.TyrePositionid)
<div class="widget-wrap">
    <div class="row">
        <div class="col-sm-3">
            <div class="form-group">
                @Html.LabelFor(model => model.VehicleTypeId, new { @class = "label" })
                <div class="select">
                    @Html.DropDownListFor(model => model.VehicleTypeId, new SelectList(ViewBag.VehicleTypeList, "Value", "Name"), "Select Vehicle Type", new { @class = "form-control", @id = "ddlVehicleType" })
                    <i></i>
                </div>
                @Html.ValidationMessageFor(model => model.VehicleTypeId)
            </div>
        </div>
        <div class="col-sm-3">
            <div class="form-group">
                @Html.LabelFor(model => model.PositionCategoryId, new { @class = "label" })
                <div class="select">
                    @Html.DropDownListFor(model => model.PositionCategoryId, new SelectList(ViewBag.PositionCategoryTypeList, "Value", "Name"), "Select PositionCategory", new { @class = "form-control", @id = "ddlPositionCategory" })
                    <i></i>
                </div>
                @Html.ValidationMessageFor(model => model.PositionCategoryId)

            </div>
        </div>
        <div class="col-sm-3">
            <div class="form-group">
                @Html.LabelFor(model => model.PositionShortCode, new { @class = "label" })
                <div class="input">
                    @Html.TextBoxFor(model => model.PositionShortCode, new { @class = "form-control", @id = "txtPositionShortCode" })
                </div>
                @Html.ValidationMessageFor(model => model.PositionShortCode)
            </div>
        </div>
        <div class="col-sm-3">
            <div class="form-group">
                @Html.LabelFor(model => model.TyrePositionDescription, new { @class = "label" })
                <div class="input">
                    @Html.TextBoxFor(model => model.TyrePositionDescription, new { @class = "form-control", @id = "txtTyrePositionDescription" })
                </div>
                @Html.ValidationMessageFor(model => model.TyrePositionDescription)
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, new { @class = "label" })
                <label class="checkbox">
                    @Html.CheckBoxFor(model => model.IsActive)
                    <i></i>
                </label>
            </div>
        </div>
    </div>

    <div class="form-footer">
        <button type="submit" class="btn btn-success primary-btn" tabindex="3">Create</button>
    </div>
</div>

}
<script>
    $(document).ready(function () {
        SetPageLoad('TyrePosition', 'Update', 'ddlVehicleType', 'Goto List', '@Url.Action("Index")', 'Add New', '@Url.Action("Insert")', 'View Detail', '@Url.Action("View", new { id = Model.TyrePositionid })');
    });
</script>

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/TyrePosition/View.cshtml
@model CodeLock.Models.MasterTyrePosition
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="widget-wrap">
    <div class="row">
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.TyrePositionid)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.TyrePositionid)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.VehicleTypeId)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.VehicleTypeName)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.PositionCategoryId)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.PositionCategoryName)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.PositionShortCode)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.PositionShortCode)
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.TyrePositionDescription)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.TyrePositionDescription)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.IsActive)
                </dt>
                <dd>
                    @Html.YesNo(Model.IsActive)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.EntryByName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.EntryByName)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.EntryDate)
                </dt>
                <dd>
                    @Model.EntryDate.ToDisplayDateTime()
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.UpdateByName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.UpdateByName)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.UpdateDate)
                </dt>
                <dd>
                    @Model.UpdateDate.ToDisplayDateTime()
                </dd>
            </dl>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        SetPageLoad('TyrePosition', 'View Detail', '', 'Goto List', '@Url.Action("Index")', 'Add New', '@Url.Action("Insert")', 'Update', '@Url.Action("Update", new { id = Model.TyrePositionid })');
    });
</script>