MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Controllers/VehicleColdChainRateController.cs
using CodeLock.Areas.Master.Repository;
using CodeLock.Models;
using System.Net;
using System.Web.Mvc;

namespace CodeLock.Areas.Master.Controllers
{
  public class VehicleColdChainRateController : Controller
  {
    private readonly IVehicleColdChainRateRepository vehicleColdChainRateRepository;

    public VehicleColdChainRateController()
    {
    }

    public VehicleColdChainRateController(
      IVehicleColdChainRateRepository _vehicleColdChainRateRepository)
    {
      this.vehicleColdChainRateRepository = _vehicleColdChainRateRepository;
    }

    public ActionResult Index()
    {
      return (ActionResult) this.View((object) this.vehicleColdChainRateRepository.GetAll());
    }

    public ActionResult Insert(short? id)
    {
      MasterVehicleColdChainRate vehicleColdChainRate = new MasterVehicleColdChainRate();
      short? nullable = id;
      if ((nullable.HasValue ? new int?((int) nullable.GetValueOrDefault()) : new int?()).HasValue)
        return (ActionResult) this.View((object) this.vehicleColdChainRateRepository.GetById(id.Value));
      return (ActionResult) this.View((object) vehicleColdChainRate);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Insert(
      MasterVehicleColdChainRate objMasterVehicleColdChainRate)
    {
      if (!this.ModelState.IsValid)
        return (ActionResult) this.View((object) objMasterVehicleColdChainRate);
      objMasterVehicleColdChainRate.EntryBy = SessionUtility.LoginUserId;
      objMasterVehicleColdChainRate.UpdateBy = new short?(SessionUtility.LoginUserId);
      this.vehicleColdChainRateRepository.InsertUpdate(objMasterVehicleColdChainRate);
      return (ActionResult) this.RedirectToAction("View", (object) new
      {
        id = objMasterVehicleColdChainRate.VehicleId
      });
    }

    public ActionResult View(short? id)
    {
      short? nullable = id;
      if (!(nullable.HasValue ? new int?((int) nullable.GetValueOrDefault()) : new int?()).HasValue)
        return (ActionResult) new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      return (ActionResult) this.View((object) this.vehicleColdChainRateRepository.GetById(id.Value));
    }

    public JsonResult GetById(short id)
    {
      return this.Json((object) this.vehicleColdChainRateRepository.GetById(id), JsonRequestBehavior.AllowGet);
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing)
        this.vehicleColdChainRateRepository.Dispose();
      base.Dispose(disposing);
    }
  }
}

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/VehicleColdChainRate/Index.cshtml
@model IEnumerable<CodeLock.Models.MasterVehicleColdChainRate>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="widget-wrap material-table-widget">
    <table id="dtVehicleColdChainRate">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.VehicleNo)
                </th>
                <th data-hide="phone">
                    @Html.DisplayNameFor(model => model.IsActive)
                </th>
                <th class="td-center" data-sort-ignore="true" data-hide="phone">Action</th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.OutsideCityDryKmpl)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.WithinCityDryKmpl)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.OutsideCityReeferKmpl)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.WithinCityReeferKmpl)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.OutsideCityEmptyKmpl)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.WithinCityEmptyKmpl)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.EntryBy)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.EntryDate)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.UpdateBy)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.UpdateDate)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th>
                        @Html.DisplayFor(modelItem => item.VehicleNo)
                    </th>
                    <td>
                        @Html.Label("", item.IsActive == true ? "Yes" : "No", new { @class = item.IsActive == true ? "label label-success" : "label label-default" })
                    </td>
                    <td class="td-center">
                        <div class="btn-toolbar" role="toolbar">
                            <div class="btn-group" role="group">
                                <a class="btn btn-default btn-sm m-user-edit" href="@Url.Action("Insert", new { id = item.VehicleId })"><span class="zmdi zmdi-edit"></span></a>
                                <a class="btn btn-default btn-sm m-user-edit" href="@Url.Action("View", new { id = item.VehicleId })"><span class="fa fa-file"></span></a>
                            </div>
                        </div>
                    </td>
                    <td style="display:none">
                        @Html.DisplayFor(model => item.OutsideCityDryKmpl)
                    </td>
                    <td style="display:none">
                        @Html.DisplayFor(model => item.WithinCityDryKmpl)
                    </td>
                    <td style="display:none">
                        @Html.DisplayFor(model => item.OutsideCityReeferKmpl)
                    </td>
                    <td style="display:none">
                        @Html.DisplayFor(model => item.WithinCityReeferKmpl)
                    </td>
                    <td style="display:none">
                        @Html.DisplayFor(model => item.OutsideCityEmptyKmpl)
                    </td>
                    <td style="display:none">
                        @Html.DisplayFor(model => item.WithinCityEmptyKmpl)
                    </td>
                    <td style="display:none">
                        @Html.DisplayFor(model => item.EntryByName)
                    </td>
                    <td style="display:none">
                        @item.EntryDate.ToDisplayDateTime()
                    </td>
                    <td style="display:none">
                        @Html.DisplayFor(model => item.UpdateByName)
                    </td>
                    <td style="display:none">
                        @item.UpdateDate.ToDisplayDateTime()
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        SetPageLoad('KMPL for Cold Chain Master', 'List', 'filter', 'Add New', '@Url.Action("Insert")');
        LoadDataTable('dtVehicleColdChainRate', true, true, true);
    });
</script>

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/VehicleColdChainRate/Insert.cshtml
@model CodeLock.Models.MasterVehicleColdChainRate
@using Secure_Coding.MvcSecurityExtensions;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Insert", "VehicleColdChainRate", FormMethod.Post, new { @class = "j-forms" }))
{
    @Html.AntiForgeryToken()
    <div class="widget-wrap">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.VehicleNo, new { @class = "label" })
                    <div class="input">
                        @Html.HiddenFor(model => model.VehicleId, new { @id = "hdnVehicleId" })
                        @Html.TextBoxFor(model => model.VehicleNo, new { @class = "form-control", @id = "txtVehicleNo" })
                    </div>
                    @Html.ValidationMessageFor(model => model.VehicleNo)
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, new { @class = "label" })
                    <label class="checkbox">
                        @Html.CheckBoxFor(model => model.IsActive, new { @id = "chkIsActive" })
                        <i></i>
                    </label>
                </div>
            </div>
        </div>
        <div class="row">
            <table id="dtVehicle">
                <thead>
                    <tr>
                        <th>Movement Type</th>
                        <th>Dry KMPL</th>
                        <th>Reefer KMPL</th>
                        <th>Empty KMPL</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>Outside City</th>
                        <td>
                            <div class="input">
                                @Html.TextBoxFor(model => model.OutsideCityDryKmpl, new { @class = "form-control numeric2", @id = "txtOutsideCityDryKmpl" })
                            </div>
                            @Html.ValidationMessageFor(m => Model.OutsideCityDryKmpl)
                        </td>
                        <td>
                            <div class="input">
                                @Html.TextBoxFor(model => model.OutsideCityReeferKmpl, new { @class = "form-control numeric2", @id = "txtOutsideCityReeferKmpl" })
                            </div>
                            @Html.ValidationMessageFor(m => Model.OutsideCityReeferKmpl)
                        </td>
                        <td>
                            <div class="input">
                                @Html.TextBoxFor(model => model.OutsideCityEmptyKmpl, new { @class = "form-control numeric2", @id = "txtOutsideCityEmptyKmpl" })
                            </div>
                            @Html.ValidationMessageFor(m => Model.OutsideCityEmptyKmpl)
                        </td>
                    </tr>
                    <tr>
                        <th>Within City</th>
                        <td>
                            <div class="input">
                                @Html.TextBoxFor(model => model.WithinCityDryKmpl, new { @class = "form-control numeric2", @id = "txtWithinCityDryKmpl" })
                            </div>
                            @Html.ValidationMessageFor(m => Model.WithinCityDryKmpl)
                        </td>
                        <td>
                            <div class="input">
                                @Html.TextBoxFor(model => model.WithinCityReeferKmpl, new { @class = "form-control numeric2", @id = "txtWithinCityReeferKmpl" })
                            </div>
                            @Html.ValidationMessageFor(m => Model.WithinCityReeferKmpl)
                        </td>
                        <td>
                            <div class="input">
                                @Html.TextBoxFor(model => model.WithinCityEmptyKmpl, new { @class = "form-control numeric2", @id = "txtWithinCityEmptyKmpl" })
                            </div>
                            @Html.ValidationMessageFor(m => Model.WithinCityEmptyKmpl)
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="form-footer">
            <button type="submit" class="btn btn-success primary-btn" tabindex="3">Create</button>
        </div>
    </div>
}
<script>
    var dtMapping;
    $(document).ready(function () {
        SetPageLoad('KMPL for Cold Chain Master', 'Insert', 'txtVehicleNo', 'Go To List', '@Url.Action("Index")');
        LoadDataTable('dtVehicle', false, false, false);
        VehicleAutoComplete('txtVehicleNo', 'hdnVehicleId');
        $('#txtVehicleNo').blur(function () { IsVehicleNoExist($('#txtVehicleNo'), $('#hdnVehicleId')); });
        $('#txtVehicleNo').readOnly($('#hdnVehicleId').val() > 0);
        $('#txtVehicleNo').blur(OnVehicleNoChange);
    });

    function OnVehicleNoChange() {
        if ($('#txtVehicleNo').val() != '') {
            var requestData = { id: $('#hdnVehicleId').val() };
            AjaxRequestWithPostAndJson('@Url.Action("", "VehicleColdChainRate")' + '/GetById', JSON.stringify(requestData), function (result) {
                $('#chkIsActive').check(result.IsActive);
                $('#txtOutsideCityDryKmpl').val(result.OutsideCityDryKmpl);
                $('#txtOutsideCityReeferKmpl').val(result.OutsideCityReeferKmpl);
                $('#txtOutsideCityEmptyKmpl').val(result.OutsideCityEmptyKmpl);
                $('#txtWithinCityDryKmpl').val(result.WithinCityDryKmpl);
                $('#txtWithinCityReeferKmpl').val(result.WithinCityReeferKmpl);
                $('#txtWithinCityEmptyKmpl').val(result.WithinCityEmptyKmpl);
            }, ErrorFunction, false);
        }
        else {
            $('#chkIsActive').uncheck();
            $('#txtOutsideCityDryKmpl').val(0);
            $('#txtOutsideCityReeferKmpl').val(0);
            $('#txtOutsideCityEmptyKmpl').val(0);
            $('#txtWithinCityDryKmpl').val(0);
            $('#txtWithinCityReeferKmpl').val(0);
            $('#txtWithinCityEmptyKmpl').val(0);
        }
    }
</script>

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/VehicleColdChainRate/View.cshtml
@model CodeLock.Models.MasterVehicleColdChainRate
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="widget-wrap">
    <div class="row">
        <div class="col-xs-4">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.VehicleNo)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.VehicleNo)
                </dd>
            </dl>
        </div>
        <div class="col-xs-4">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.IsActive)
                </dt>
                <dd>
                    @Html.YesNo(Model.IsActive)
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <table id="dtVehicle">
            <thead>
                <tr>
                    <th>Movement Type</th>
                    <th>Dry KMPL</th>
                    <th>Reefer KMPL</th>
                    <th>Empty KMPL</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>Outside City</th>
                    <td>
                        <div class="input">
                            @Html.TextBoxFor(model => model.OutsideCityDryKmpl, new { @class = "form-control textlabel numeric2", @id = "txtOutsideCityDryKmpl" })
                        </div>
                        @Html.ValidationMessageFor(m => Model.OutsideCityDryKmpl)
                    </td>
                    <td>
                        <div class="input">
                            @Html.TextBoxFor(model => model.OutsideCityReeferKmpl, new { @class = "form-control textlabel numeric2", @id = "txtOutsideCityReeferKmpl" })
                        </div>
                        @Html.ValidationMessageFor(m => Model.OutsideCityReeferKmpl)
                    </td>
                    <td>
                        <div class="input">
                            @Html.TextBoxFor(model => model.OutsideCityEmptyKmpl, new { @class = "form-control textlabel numeric2", @id = "txtOutsideCityEmptyKmpl" })
                        </div>
                        @Html.ValidationMessageFor(m => Model.OutsideCityEmptyKmpl)
                    </td>
                </tr>
                <tr>
                    <th>Within City</th>
                    <td>
                        <div class="input">
                            @Html.TextBoxFor(model => model.WithinCityDryKmpl, new { @class = "form-control textlabel numeric2", @id = "txtWithinCityDryKmpl" })
                        </div>
                        @Html.ValidationMessageFor(m => Model.WithinCityDryKmpl)
                    </td>
                    <td>
                        <div class="input">
                            @Html.TextBoxFor(model => model.WithinCityReeferKmpl, new { @class = "form-control textlabel numeric2", @id = "txtWithinCityReeferKmpl" })
                        </div>
                        @Html.ValidationMessageFor(m => Model.WithinCityReeferKmpl)
                    </td>
                    <td>
                        <div class="input">
                            @Html.TextBoxFor(model => model.WithinCityEmptyKmpl, new { @class = "form-control textlabel numeric2", @id = "txtWithinCityEmptyKmpl" })
                        </div>
                        @Html.ValidationMessageFor(m => Model.WithinCityEmptyKmpl)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="row">
        <div class="col-xs-4">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.EntryByName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.EntryByName)
                </dd>
            </dl>
        </div>
        <div class="col-xs-4">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.EntryDate)
                </dt>
                <dd>
                    @Model.EntryDate.ToDisplayDateTime()
                </dd>
            </dl>
        </div>
        <div class="col-xs-4">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.UpdateByName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.UpdateByName)
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-4">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.UpdateDate)
                </dt>
                <dd>
                    @Model.UpdateDate.ToDisplayDateTime()
                </dd>
            </dl>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        SetPageLoad('Vehicle Document', 'View Detail', '', 'Goto List', '@Url.Action("Index")', 'Add New', '@Url.Action("Insert")', 'Update', '@Url.Action("Insert", new { id = Model.VehicleId })');
        LoadDataTable('dtVehicle', false, false, false);
    });
</script>