MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Controllers/JobOrderTaskController.cs
using CodeLock.Areas.Master.Repository;
using CodeLock.Models;
using Microsoft.CSharp.RuntimeBinder;
using Secure_Coding.MvcSecurityExtensions;
using System;
using System.Collections.Generic;
using System.Net;
using System.Runtime.CompilerServices;
using System.Web.Mvc;

namespace CodeLock.Areas.Master.Controllers
{
  public class JobOrderTaskController : Controller
  {
    private readonly IJobOrderTaskRepository jobOrderTaskRepository;
    private readonly IJobOrderWorkGroupRepository jobOrderWorkGroupRepository;
    private readonly IJobOrderTaskTypeRepository jobOrderTaskTypeRepository;

    public JobOrderTaskController()
    {
    }

    public JobOrderTaskController(
      IJobOrderTaskRepository _jobOrderTaskRepository,
      IJobOrderWorkGroupRepository _jobOrderWorkGroupRepository,
      IJobOrderTaskTypeRepository _jobOrderTaskTypeRepository)
    {
      this.jobOrderTaskRepository = _jobOrderTaskRepository;
      this.jobOrderWorkGroupRepository = _jobOrderWorkGroupRepository;
      this.jobOrderTaskTypeRepository = _jobOrderTaskTypeRepository;
    }

    public ActionResult Index()
    {
      return (ActionResult) this.View((object) this.jobOrderTaskRepository.GetAll());
    }

    public ActionResult View(byte? id)
    {
      byte? nullable = id;
      if (!(nullable.HasValue ? new int?((int) nullable.GetValueOrDefault()) : new int?()).HasValue)
        return (ActionResult) new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      MasterJobOrderTask detailById = this.jobOrderTaskRepository.GetDetailById(id.Value);
      if (detailById == null)
        return (ActionResult) this.HttpNotFound();
      return (ActionResult) this.View((object) detailById);
    }


        public ActionResult Insert(byte? id)
        {
            int? nullable;
            int? nullable1;
            MasterJobOrderTask masterJobOrderTask = new MasterJobOrderTask();
            byte? nullable2 = id;
            if (nullable2.HasValue)
            {
                nullable1 = new int?((int)nullable2.GetValueOrDefault());
            }
            else
            {
                nullable = null;
                nullable1 = nullable;
            }
            nullable = nullable1;
            if (nullable.HasValue)
            {
                masterJobOrderTask = this.jobOrderTaskRepository.GetDetailById(id.Value);
            }
            ((dynamic)base.ViewBag).WorkGroupList = this.jobOrderWorkGroupRepository.GetWorkGroupList();
            ((dynamic)base.ViewBag).TaskTypeList = this.jobOrderTaskTypeRepository.GetTaskTypeList();
            return base.View(masterJobOrderTask);
        }

        [HttpPost]
        [ValidateAntiModelInjection("TaskId")]
        public ActionResult Insert(MasterJobOrderTask objTask)
        {
            Response response;
            ActionResult action;
            if (base.ModelState.IsValid)
            {
                objTask.EntryBy = SessionUtility.LoginUserId;
                objTask.UpdateBy = new short?(SessionUtility.LoginUserId);
                response = (objTask.TaskId <= 0 ? this.jobOrderTaskRepository.Insert(objTask) : this.jobOrderTaskRepository.Update(objTask));
                if (response.IsSuccessfull)
                {
                    action = base.RedirectToAction("View", new { id = response.DocumentId });
                    return action;
                }
                base.TempData["result"] = response;
            }
             ((dynamic)base.ViewBag).WorkGroupList = this.jobOrderWorkGroupRepository.GetWorkGroupList();
            ((dynamic)base.ViewBag).TaskTypeList = this.jobOrderTaskTypeRepository.GetTaskTypeList();
            action = base.View(objTask);
            return action;
        }

        public JsonResult IsTaskAvailable(
      byte workGroupId,
      byte taskTypeId,
      string task,
      short taskId)
    {
      return this.Json((object) this.jobOrderTaskRepository.IsTaskAvailable(workGroupId, taskTypeId, task, taskId));
    }

    public JsonResult GetTaskDescriptionListByWorkGroupIdAndTaskTypeId(
      byte workGroupId,
      byte taskTypeId)
    {
      return this.Json((object) this.jobOrderTaskRepository.GetTaskDescriptionListByWorkGroupIdAndTaskTypeId(workGroupId, taskTypeId));
    }

    public JsonResult GetEstimatedLabourHoursByTaskId(short taskId)
    {
      return this.Json((object) this.jobOrderTaskRepository.GetEstimatedLabourHoursByTaskId(taskId));
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing)
        this.jobOrderTaskRepository.Dispose();
      base.Dispose(disposing);
    }
  }
}

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/JobOrderTask/Index.cshtml
@model IEnumerable<CodeLock.Models.MasterJobOrderTask>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="widget-wrap material-table-widget">
    <table id="dtTask">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(m => m.Task)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.WorkGroupId)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.TaskTypeId)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.IsActive)
                </th>
                <th class="td-center" data-sort-ignore="true" data-hide="phone">Action</th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.EstimatedLabourHours)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.EntryByName)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.EntryDate)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.UpdateByName)
                </th>
                <th style="display:none">
                    @Html.DisplayNameFor(model => model.UpdateDate)
                </th>
            </tr>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th>
                        @Html.DisplayFor(m => item.Task)
                    </th>
                    <td>
                        @Html.DisplayFor(m => item.WorkGroup)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.TaskType)
                    </td>
                    <td>
                        @Html.Label("", item.IsActive == true ? "Yes" : "No", new { @class = item.IsActive == true ? "label label-success" : "label label-default" })
                    </td>
                    <td class="td-center">
                        <div class="btn-toolbar" role="toolbar">
                            <div class="btn-group" role="group">
                                <a class="btn btn-default btn-sm m-user-edit" href="@Url.Action("Insert", new { id = item.TaskId })"><span class="zmdi zmdi-edit"></span></a>
                                <a class="btn btn-default btn-sm m-user-edit" href="@Url.Action("View", new { id = item.TaskId })"><span class="fa fa-file"></span></a>
                            </div>
                        </div>
                    </td>
                    <td style="display:none">
                        @Html.DisplayFor(modelItem => item.EstimatedLabourHours)
                    </td>
                    <td style="display:none">
                        @Html.DisplayFor(modelItem => item.EntryByName)
                    </td>
                    <td style="display:none">
                        @item.EntryDate.ToDisplayDateTime()
                    </td>
                    <td style="display:none">
                        @Html.DisplayFor(modelItem => item.UpdateByName)
                    </td>
                    <td style="display:none">
                        @item.UpdateDate.ToDisplayDateTime()
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        SetPageLoad('Task', 'List', '', 'Add New', '@Url.Action("Insert")');
        LoadDataTable('dtTask', true, true, true);
        $('[id=dtTask_filter]').find('input').focus();
    });
</script>

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/JobOrderTask/Insert.cshtml
@model CodeLock.Models.MasterJobOrderTask
@using CodeLock.Models
@using Secure_Coding.MvcSecurityExtensions;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Insert", "JobOrderTask", FormMethod.Post, new { @class = "j-forms", @id = "j-forms" }))
{
    @Html.AntiForgeryToken()
    @Html.AntiModelInjectionFor(m => m.TaskId)
    @Html.HiddenFor(m => m.TaskId, new { @id = "hdnTaskId" })
    <div class="widget-wrap">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.WorkGroupId, new { @class = "label" })
                    <div class="select">
                        @Html.DropDownListFor(model => model.WorkGroupId, new SelectList(ViewBag.WorkGroupList, "Value", "Name"), "Select Work Group", new { @class = "form-control", @id = "ddlWorkGroupId" })
                        <i></i>
                    </div>
                    @Html.ValidationMessageFor(model => model.WorkGroupId)

                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.TaskTypeId, new { @class = "label" })
                    <div class="select">
                        @Html.DropDownListFor(model => model.TaskTypeId, new SelectList(ViewBag.TaskTypeList, "Value", "Name"), "Select Task Type", new { @class = "form-control", @id = "ddlTaskTypeId" })
                        <i></i>
                    </div>
                    @Html.ValidationMessageFor(model => model.TaskTypeId)

                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Task, new { @class = "label" })
                    <div class="input">
                        @Html.TextBoxFor(model => model.Task, new { @class = "form-control text-uppercase", @id = "txtTask" })
                    </div>
                    @Html.ValidationMessageFor(model => model.Task)
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.EstimatedLabourHours, new { @class = "label" })
                    <div class="input">
                        @Html.TextBoxFor(model => model.EstimatedLabourHours, new { @class = "form-control numeric" })
                    </div>
                    @Html.ValidationMessageFor(model => model.EstimatedLabourHours)
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, new { @class = "label" })
                    <label class="checkbox">
                        @Html.CheckBoxFor(model => model.IsActive)
                        <i></i>
                    </label>
                </div>
            </div>
        </div>
        <div class="form-footer">
            <button type="submit" id="btnSubmit" class="btn btn-success primary-btn" tabindex="0"></button>
        </div>
    </div>
}
<script>
    var hdnTaskId, ddlWorkGroupId, ddlTaskTypeId, txtTask, btnSubmit;
    $(document).ready(function () {
        hdnTaskId = $('#hdnTaskId');
        ddlWorkGroupId = $('#ddlWorkGroupId');
        ddlTaskTypeId = $('#ddlTaskTypeId');
        txtTask = $('#txtTask');
        btnSubmit = $('#btnSubmit');
        ddlWorkGroupId.change(function () { return IsTaskAvailable(ddlWorkGroupId); });
        ddlTaskTypeId.change(function () { return IsTaskAvailable(ddlTaskTypeId); });
        txtTask.blur(function () { return IsTaskAvailable(txtTask); });
        OnPageLoad();
    });

    function OnPageLoad() {
        var isAdd = true;
        if (hdnTaskId.val() != 0)
            isAdd = false;

        if (isAdd == false)
            SetPageLoad('Task', 'Edit', 'ddlWorkGroupId', 'Go To List', '@Url.Action("Index")');
        else
            SetPageLoad('Task', 'Add', 'ddlWorkGroupId', 'Go To List', '@Url.Action("Index")');

        btnSubmit.html((isAdd ? 'Create' : 'Update'));
    }

    function IsTaskAvailable(obj) {
        if (ddlWorkGroupId.val() != '' && ddlTaskTypeId.val() != '' && txtTask.val() != '') {
            var requestData = { workGroupId: ddlWorkGroupId.val(), taskTypeId: ddlTaskTypeId.val(), task: txtTask.val(), taskId: hdnTaskId.val() };
            AjaxRequestWithPostAndJson('@Url.Action("IsTaskAvailable")', JSON.stringify(requestData), function (result) {
                if (result) {
                    ShowMessage('Task already exists');
                    obj.val('');
                    return false;
                }
            }, ErrorFunction, false);
        }
    }
</script>

MLPL_SVN/MLPL_SVN/trunk/SourceCode/CodeLock/Areas/Master/Views/JobOrderTask/View.cshtml
@model CodeLock.Models.MasterJobOrderTask
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="widget-wrap">
    <div class="row">
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.Task)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Task)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.WorkGroupId)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.WorkGroup)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.TaskTypeId)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.TaskType)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.EstimatedLabourHours)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.EstimatedLabourHours)
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.IsActive)
                </dt>
                <dd>
                    @Html.YesNo(Model.IsActive)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.EntryBy)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.EntryByName)
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.EntryDate)
                </dt>
                <dd>
                    @Model.EntryDate.ToDisplayDateTime()
                </dd>
            </dl>
        </div>
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.UpdateBy)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.UpdateByName)
                </dd>
            </dl>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-3">
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.UpdateDate)
                </dt>
                <dd>
                    @Model.UpdateDate.ToDisplayDateTime()
                </dd>
            </dl>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        SetPageLoad('Task', 'View', '', 'Add New', '@Url.Action("Insert")', 'Update', '@Url.Action("Insert", new { id = Model.TaskId })', 'Go To List', '@Url.Action("Index")');
    });
</script>